module.exports = {
  apps: [
    {
      name: 'mediprotect-app',
      script: '.output/server/index.mjs',
      cwd: '/var/www/app_mediprotect',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        HOST: '0.0.0.0',
        NUXT_JWT_SECRET: 'mediprotect_jwt_secret_key_2026',
        NUXT_DATABASE_URL: 'postgresql://postgres:Mobiltoo111213@db.mruezojnfgkdhtgxwgmv.supabase.co:5432/postgres',
        NUXT_WHATSAPP_GATEWAY_URL: 'http://127.0.0.1:8080',
        NUXT_WHATSAPP_INSTANCE_NAME: 'mediprotect',
        NUXT_WHATSAPP_GATEWAY_APIKEY: '',
        NUXT_WHATSAPP_WEBHOOK_APIKEY: 'MpWebhook_2026_cambiar',
        NUXT_WHATSAPP_WEBHOOK_ALLOWED_IPS: '',
        NUXT_VALIDA_CURP_TOKEN: 'pruebas',
        DATABASE_URL: 'postgresql://postgres:Mobiltoo111213@db.mruezojnfgkdhtgxwgmv.supabase.co:5432/postgres',
        JWT_SECRET: 'mediprotect_jwt_secret_key_2026',
        JWT_EXPIRES_IN: '7d',
        SMTP_USER: 'b70b6d001@smtp-brevo.com',
        SMTP_PASS: 'xsmtpsib-0b83288d751eeeae05135d1afb984163468f3811e8d5163daa7693da9af6fd9e-4C0fauoTvL78Z57T',
        SMTP_HOST: 'smtp-relay.brevo.com',
        SMTP_PORT: '465',
        SMTP_FROM: 'agente@mediprotect.com.mx'
      },
      out_file: '/var/log/mediprotect/app-out.log',
      error_file: '/var/log/mediprotect/app-error.log',
      merge_logs: true,
      time: true,
      autorestart: true,
      max_memory_restart: '512M',
      kill_timeout: 5000
    },
    {
      name: 'evolution-api',
      script: 'dist/server.js',
      cwd: '/var/www/evolution-api',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: '8080',
        SERVER_URL: 'http://127.0.0.1:8080',
        AUTHENTICATION_API_KEY: '',
        DATABASE_ENABLED: 'true',
        DATABASE_PROVIDER: 'postgresql',
        DATABASE_CONNECTION_URI: 'postgresql://postgres:Mobiltoo111213@db.mruezojnfgkdhtgxwgmv.supabase.co:5432/postgres',
        DATABASE_SAVE_DATA_INSTANCE: 'true',
        DATABASE_SAVE_DATA_CREATE_INSTANCE: 'false',
        DATABASE_SAVE_DATA_NEW_MESSAGE: 'true',
        DATABASE_SAVE_MESSAGE_UPDATE: 'true',
        DATABASE_SAVE_DATA_CONTACTS: 'true',
        DATABASE_SAVE_DATA_CHATS: 'true',
        DATABASE_SAVE_DATA_LABELS: 'true',
        DATABASE_SAVE_INSTANCES: 'true',
        DATABASE_SAVE_INSTANCES_SESSION: 'true',
        DATABASE_SAVE_INSTANCES_LOGS: 'true',
        WEBHOOK_GLOBAL_ENABLED: 'true',
        WEBHOOK_GLOBAL_URL: 'https://app.mediprotect.com.mx/whook/wame',
        WEBHOOK_GLOBAL_EVENTS: 'messages.upsert',
        WEBHOOK_GLOBAL_HEADERS: '{"x-mediprotect-apikey":"MpWebhook_2026_cambiar"}'
      },
      out_file: '/var/log/mediprotect/evolution-api-out.log',
      error_file: '/var/log/mediprotect/evolution-api-error.log',
      merge_logs: true,
      time: true,
      autorestart: true,
      max_memory_restart: '600M',
      kill_timeout: 5000
    }
  ]
}