const pg = require('pg')
const pool = new pg.Pool({ connectionString: 'postgresql://postgres:Mobiltoo111213@db.mruezojnfgkdhtgxwgmv.supabase.co:5432/postgres' })
;(async () => {
  const r1 = await pool.query("SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_name = 'pagos' ORDER BY ordinal_position")
  console.log('PAGOS:')
  r1.rows.forEach(r => console.log('  ' + r.column_name + ' ' + r.data_type + ' nullable=' + r.is_nullable))
  const r2 = await pool.query("SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'paquetes' ORDER BY ordinal_position")
  console.log('PAQUETES:')
  r2.rows.forEach(r => console.log('  ' + r.column_name + ' ' + r.data_type))
  const r3 = await pool.query("SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'planes_cobertura' ORDER BY ordinal_position")
  console.log('PLANES_COBERTURA:')
  r3.rows.forEach(r => console.log('  ' + r.column_name + ' ' + r.data_type))
  await pool.end()
})()
